### ISSUE TITLE
Postgres-gen-dao find() the same rows

### ISSUE THREAD

**Issue by DeoMortis** [evs-chris/postgres-gen-dao#1]
Hi. 

I have an issue using postgres-gen-dao. The find() function seems to return correct amount of rows, but every row is the same.

My test case:
TEST_TABLE_01 has one column. There are 14 rows with values TEST_VALUE_01 to TEST_VALUE_14

```
var filters = dao({ db: pg_gen, table: 'test_table_01' });

filters.find().then(function(result){
    console.log('#PG-GEN RESULT:');
    console.log(result);
  });
```

And my result is

```
# PG-GEN RESULT:
[ { _generated_loaded: true, testColumn: 'TEST_VALUE_01' },
  { _generated_loaded: true, testColumn: 'TEST_VALUE_01' },
  { _generated_loaded: true, testColumn: 'TEST_VALUE_01' },
  { _generated_loaded: true, testColumn: 'TEST_VALUE_01' },
  { _generated_loaded: true, testColumn: 'TEST_VALUE_01' },
  { _generated_loaded: true, testColumn: 'TEST_VALUE_01' },
  { _generated_loaded: true, testColumn: 'TEST_VALUE_01' },
  { _generated_loaded: true, testColumn: 'TEST_VALUE_01' },
  { _generated_loaded: true, testColumn: 'TEST_VALUE_01' },
  { _generated_loaded: true, testColumn: 'TEST_VALUE_01' },
  { _generated_loaded: true, testColumn: 'TEST_VALUE_01' },
  { _generated_loaded: true, testColumn: 'TEST_VALUE_01' },
  { _generated_loaded: true, testColumn: 'TEST_VALUE_01' },
  { _generated_loaded: true, testColumn: 'TEST_VALUE_01' } ]
```

A "classic" approach, using pg.Client, and then query returns correct values in testColumn (01 to 14).

Is there something i am missing, or is there some kind of a bug?

**Comment by evs-chris** [comment]
That's definitely a bug. I'll get a fix out soon, but if your tables have a primary key, you shouldn't run into it. The loading logic caches records by primary key, and the bug makes all of them have the same key in this case (none).

**Comment by DeoMortis** [comment]
Thanks!

You're right. My table doesn't have primary key. I'm looking forward to the fix.
Cheers.

**Comment by evs-chris** [comment]
I have pushed 0.11.0, which has the fix for this along with basic support for inserting, updating, and deleting records in keyless tables. If you don't mind, give it a go and let me know if it works for you.

**Comment by DeoMortis** [comment]
Works Great. Thanks!
